openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts book
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: >
    A contact storage application is an application that allows users to conveniently store and manage their contacts. The main functions of such an application include:
    1. Adding contacts. The user can add new contacts by specifying their name and phone number.
    2. Viewing contacts. Viewing a list of all saved contacts is available in the application.
    3. Editing and deleting contacts. The user can edit existing contacts by making changes to their information or removing them from the list.
    4. Contact search. The application provides the ability to quickly search for contacts by name or phone number, which makes it easier to find the necessary information.
    5. Storage in regional storage. Contacts are stored in regional storage, which allows users to store their data and access it from different devices.
# tags:
  # теги, що ви будете використовувати
servers:
  - url: <http://localhost:3000>
  # - url: #посилання на задеплоєний сайт
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
  /contacts:
    post: 
      $ref: ../swagger/paths/contacts/post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
